# .github/dependabot.yml
# Docs: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      production-minor-and-patch:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    cooldown:
      default-days: 7
